version: 2
localCheckout: &localCheckout
  run: |-
    PROJECT_PATH=$(cd ${CIRCLE_WORKING_DIRECTORY}; pwd)
    mkdir -p ${PROJECT_PATH}
    cd /tmp/_circleci_local_build_repo 
    git ls-files -z | xargs -0 -s 2090860 tar -c | tar -x -C ${PROJECT_PATH} 
    cp -a /tmp/_circleci_local_build_repo/.git ${PROJECT_PATH}

checkout: &checkout
  checkout

jobs:
  build:
    docker:
      - image: circleci/node:10.16.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: git submodule update
      - run: npm install bower; PATH=${PATH}":$(pwd)/node_modules/.bin/"
      - run: npm install hexo-cli
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - add_ssh_keys: 
          fingerprints:
            - "35:e8:27:96:3b:a5:61:0d:ce:f3:94:0e:6c:a6:a0:56"
      - deploy:
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            npm run clean
            npm run deploy
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
#      - test 
